2022-04-15 02:08:37,791 ERROR: Exception on /forum [GET] [in Z:\_\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "Z:\_\microblog\app\main\routes.py", line 53, in forum
    return render_template('forum.html', title=_('Programme Forum'))
  File "Z:\_\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "Z:\_\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "Z:\_\microblog\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "Z:\_\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "Z:\_\microblog\app\templates\forum.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "Z:\_\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'html'
    {% block body -%}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 26, in block 'body'
    {% block content -%}
  File "Z:\_\microblog\app\templates\base.html", line 237, in block 'content'
    {% block current_app_content %}{% endblock %}
  File "Z:\_\microblog\app\templates\forum.html", line 31, in block 'current_app_content'
    <a href="{{ url_for('main.forum/'+station['id']) }}"><h1>>{{ station['name'] }}</h1></a>
  File "Z:\_\microblog\venv\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "Z:\_\microblog\venv\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "Z:\_\microblog\venv\lib\site-packages\werkzeug\routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.forum/S01'. Did you mean 'main.forum' instead?
2022-04-15 02:08:38,134 ERROR: Exception on /forum [GET] [in Z:\_\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "Z:\_\microblog\app\main\routes.py", line 53, in forum
    return render_template('forum.html', title=_('Programme Forum'))
  File "Z:\_\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "Z:\_\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "Z:\_\microblog\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "Z:\_\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "Z:\_\microblog\app\templates\forum.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "Z:\_\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'html'
    {% block body -%}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 26, in block 'body'
    {% block content -%}
  File "Z:\_\microblog\app\templates\base.html", line 237, in block 'content'
    {% block current_app_content %}{% endblock %}
  File "Z:\_\microblog\app\templates\forum.html", line 31, in block 'current_app_content'
    <a href="{{ url_for('main.forum/'+station['id']) }}"><h1>>{{ station['name'] }}</h1></a>
  File "Z:\_\microblog\venv\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "Z:\_\microblog\venv\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "Z:\_\microblog\venv\lib\site-packages\werkzeug\routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.forum/S01'. Did you mean 'main.forum' instead?
2022-04-15 02:08:38,446 ERROR: Exception on /forum [GET] [in Z:\_\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "Z:\_\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "Z:\_\microblog\app\main\routes.py", line 53, in forum
    return render_template('forum.html', title=_('Programme Forum'))
  File "Z:\_\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "Z:\_\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "Z:\_\microblog\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "Z:\_\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "Z:\_\microblog\app\templates\forum.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "Z:\_\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'html'
    {% block body -%}
  File "Z:\_\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 26, in block 'body'
    {% block content -%}
  File "Z:\_\microblog\app\templates\base.html", line 237, in block 'content'
    {% block current_app_content %}{% endblock %}
  File "Z:\_\microblog\app\templates\forum.html", line 31, in block 'current_app_content'
    <a href="{{ url_for('main.forum/'+station['id']) }}"><h1>>{{ station['name'] }}</h1></a>
  File "Z:\_\microblog\venv\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "Z:\_\microblog\venv\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "Z:\_\microblog\venv\lib\site-packages\werkzeug\routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.forum/S01'. Did you mean 'main.forum' instead?
